/**
 * Demo URL catalog generator.
 *
 * Run: `npm run demo:urls` (writes docs/generated/demo-urls.md and prints the table).
 * Point it at a deployed host with `BASE=https://... npm run demo:urls`.
 *
 * Derived entirely from FLOW_DEFS / EMBED_VARIANTS / CONCEPT_EMBED_FLOW_LAYOUTS, so
 * the catalog cannot drift from the registry — adding a flow with a slug adds a row
 * here for free. Validates data only (no React), so it runs in plain node via tsx.
 */
import { writeFileSync } from "node:fs"
import { FLOW_DEFS } from "../lib/ask-nanci/data/flows.concept"
import {
  EMBED_VARIANTS,
  parseMode,
  CONCEPT_EMBED_FLOW_LAYOUTS,
} from "../lib/ask-nanci/embed-demo-config"

const PROD_BASE = "https://ask-nanci.vercel.app"
const BASE = process.env.BASE ?? "http://localhost:3000"

/**
 * Where each URL is embedded in the wild. Deployment facts, not registry facts, so
 * this is the one part of the catalog maintained by hand.
 *
 * NOT authoritative — it's what's been found, not what exists. `../webflow` is a
 * one-commit snapshot that can lag the published Webflow site, and an embed on a page
 * in neither repo would not appear here at all. The complete answer is Vercel referrer
 * data for the `aperia-ask-nanci-embed` project (Web Analytics → Referrers, or the
 * `Referer` header in runtime logs). Reconcile against that before trusting this list.
 */
type Embed = { query: string; where: string; note?: string }

const EXPLICIT_EMBEDS: Embed[] = [
  { query: "mode=business-owner", where: "production site (page unconfirmed)" },
  { query: "mode=clover", where: "production site (page unconfirmed)" },
  { query: "mode=vw", where: "production site (page unconfirmed)" },
  { query: "mode=concept-embed&flow=2", where: "production site (page unconfirmed)" },
  { query: "mode=concept-embed&flow=11", where: "production site (page unconfirmed)" },
  // `mode=detect` used to be listed here, embedded at
  // ../webflow/ask-nanci-v3-storybrand_6_dark.html:1561 and flagged broken: it was never
  // a case in parseMode, so it fell through to the default app instead of an embed.
  // Removed 2026-08-12 — the reference is gone from ../webflow entirely. Do not re-add
  // the mode; nothing points at it.
]

// Every flow in the Merchant Money group (`section: "merchant"`) is live. Derived rather
// than listed, so a new merchant flow is marked live the moment it gets a slug.
const merchantEmbeds = (): Embed[] =>
  FLOW_DEFS.filter((f) => f.section === "merchant")
    .flatMap((f) => {
      const slug = f.slug ?? (CONCEPT_EMBED_FLOW_LAYOUTS[String(f.num)] ? String(f.num) : null)
      return slug ? [{ query: `mode=concept-embed&flow=${slug}`, where: `Merchant Money group — ${f.title}` }] : []
    })
    .sort((a, b) => a.query.localeCompare(b.query, undefined, { numeric: true }))

const seen = new Set(EXPLICIT_EMBEDS.map((e) => e.query))
const EMBEDDED_IN: Embed[] = [...EXPLICIT_EMBEDS, ...merchantEmbeds().filter((e) => !seen.has(e.query))]

const url = (q: string) => (q ? `${BASE}/?${q}` : `${BASE}/`)
const embeddedQueries = new Set(EMBEDDED_IN.map((e) => e.query))
const liveMark = (q: string) => (embeddedQueries.has(q) ? " **live**" : "")

const lines: string[] = []
const p = (s = "") => lines.push(s)

p("# Demo URLs")
p()
p("**Read when:** looking up a demo or embed URL")
p()
p("<!-- Generated by `npm run demo:urls` — do not edit by hand. -->")
p()
p(`Base: \`${BASE}\` (override with \`BASE=https://... npm run demo:urls\`).`)
p("**live** marks an embed running on the production site — treat its code paths as production-facing.")
p()

// ── Modes ────────────────────────────────────────────────────────────────────
p("## Modes")
p()
p("| URL | Embed | Concept engine | Notes |")
p("|---|---|---|---|")
const MODE_NOTES: Record<string, string> = {
  "": "Default app — sidebar, KB panel, sessions",
  concept: "Panel demo with the welcome card catalog",
  "concept-nav": "Alias of `concept` — the hover-rail sidebar it trialled is now app-wide; kept so shared links keep working",
  titan: "Duplicate of `concept` — same welcome card catalog and panel demo — wearing the Titan brand",
  tib: "Full app (sidebar, sessions, KB panel) wearing the TIB brand",
  woodforest: "Full app (sidebar, sessions, KB panel) wearing the Woodforest brand",
  placeholder: "Full app wearing the white-label placeholder brand — swap the logo + theme block to stand up a new one",
  onboarding: "Default app, but the onboarding dialog opens on every load and finishing it records nothing — so it can be demoed repeatedly without clearing localStorage",
}
for (const mode of ["", ...EMBED_VARIANTS, "concept", "concept-nav", "titan", "titan-embed", "tib", "woodforest", "placeholder", "onboarding"]) {
  const q = mode ? `mode=${mode}` : ""
  const { isEmbed, isConceptVersion } = parseMode(mode || null)
  const note = MODE_NOTES[mode] ?? (isConceptVersion ? "Panel demo, embeddable" : "Chat-only embed")
  p(`| \`${url(q)}\`${liveMark(q)} | ${isEmbed ? "yes" : "no"} | ${isConceptVersion ? "yes" : "no"} | ${note} |`)
}
p()
p("Any other `?mode=` value falls through to the default app.")
p()

// ── Embeddable flows ─────────────────────────────────────────────────────────
type Entry = { slug: string; flow: (typeof FLOW_DEFS)[number]; alt: boolean }
const entries: Entry[] = FLOW_DEFS.flatMap((flow) => [
  ...(flow.slug ? [{ slug: flow.slug, flow, alt: false }] : []),
  ...(flow.altEntries?.map((e) => ({ slug: e.slug, flow, alt: true })) ?? []),
]).sort((a, b) => Number(a.slug) - Number(b.slug) || a.slug.localeCompare(b.slug))

p("## Embeddable concept flows")
p()
p("`?mode=concept-embed&flow=<slug>` loads the flow in the compact widget. It does **not**")
p("play on load — the **Ask** button in the top bar starts it.")
p()
p("Add `&autoplay` to play it on load instead. The param is opt-in, so every URL below")
p("behaves exactly as it does today until the param is added, and it is mode-agnostic:")
p("`?mode=tib&flow=2&autoplay` works the same way. `&autoplay=0` explicitly turns it off.")
p()
p("Add `&brand=generic` to drop partner branding from the two financing flows (20 and")
p("21): the product is renamed, the logo, monogram and colour go neutral, and the audit")
p("record reads \"the issuer\" / \"the lending partner\". Rates, amounts and terms are")
p("identical either way — the brand changes, the offer does not. Opt-in and mode-agnostic")
p("like `autoplay`, so a partner-facing site and a sales site can share one set of URLs")
p("with one param between them. Flows other than 20 and 21 ignore it.")
p()
p("| URL | Card | Flow | Layout |")
p("|---|---|---|---|")
for (const { slug, flow, alt } of entries) {
  const q = `mode=concept-embed&flow=${slug}`
  const layout = CONCEPT_EMBED_FLOW_LAYOUTS[slug]
  const layoutNote = layout
    ? `full app shell${layout.openMarketplace ? " + marketplace open" : ""}`
    : "compact widget"
  const title = alt ? `${flow.title} — alt entry` : flow.title
  p(`| \`${url(q)}\`${liveMark(q)} | ${flow.num} | ${title} | ${layoutNote} |`)
}
p()

// A layout override keys off the raw ?flow= param, independent of the slug lookup, so
// a destination flow reaches its layout with no slug and no autoplay. Surface those
// rather than letting them look like dead config.
const layoutOnly = Object.keys(CONCEPT_EMBED_FLOW_LAYOUTS).filter(
  (k) => !entries.some((e) => e.slug === k),
)
if (layoutOnly.length) {
  p("### Layout-only entries (no autoplay)")
  p()
  p("These have a layout override but no slug — they open a destination surface instead of playing a script.")
  p()
  p("| URL | Card | Flow |")
  p("|---|---|---|")
  for (const slug of layoutOnly) {
    const flow = FLOW_DEFS.find((f) => String(f.num) === slug)
    const q = `mode=concept-embed&flow=${slug}`
    p(`| \`${url(q)}\`${liveMark(q)} | ${flow?.num ?? "?"} | ${flow?.title ?? "unknown"} |`)
  }
  p()
}

// ── Not reachable by URL ─────────────────────────────────────────────────────
const noSlug = FLOW_DEFS.filter((f) => !f.slug && !f.altEntries?.length && !CONCEPT_EMBED_FLOW_LAYOUTS[String(f.num)])
p("## Flows with no embed URL")
p()
p(`${noSlug.length} of ${FLOW_DEFS.length} flows have no slug — reachable only via the \`?mode=concept\` welcome cards.`)
p()
for (const f of noSlug) p(`- ${f.num}. ${f.title} — ${f.badge}`)
p()

// ── Other routes ─────────────────────────────────────────────────────────────
p("## Other routes")
p()
p(`- \`${BASE}/risk\` — Aperia Risk shell. \`?alerted=\` / \`?worked=\` are read by \`QueueSummaryCard\`.`)
p()

// ── Where these are embedded ─────────────────────────────────────────────────
p("## Embedded in production")
p()
p(`Deployed at \`${PROD_BASE}\`. Anything below is production-facing — verify changes to its code`)
p("path in a browser, not just `next build`.")
p()
p("**This list is hand-maintained and incomplete by nature.** It records embeds that have been")
p("found, not every embed that exists: `../webflow` is a one-commit snapshot that can lag the")
p("published Webflow site, and a page in neither repo would not show up here. For the complete")
p(`picture use Vercel referrer data for the \`aperia-ask-nanci-embed\` project (Web Analytics →`)
p("Referrers, or the `Referer` header in runtime logs).")
p()
p("| URL | Embedded in | Status |")
p("|---|---|---|")
for (const { query, where, note } of EMBEDDED_IN) {
  p(`| \`${PROD_BASE}/?${query}\` | ${where} | ${note ?? "ok"} |`)
}
p()
const unknownMode = EMBEDDED_IN.filter((e) => e.note)
if (unknownMode.length) {
  p(`⚠️ ${unknownMode.length} embedded URL(s) above do not resolve to a valid mode — see the Modes table.`)
  p()
}

const out = lines.join("\n")
writeFileSync("docs/generated/demo-urls.md", out)
console.log(out)
console.error(
  `\n✓ wrote docs/generated/demo-urls.md — ${entries.length} embeddable flows, ${layoutOnly.length} layout-only, ${noSlug.length} card-only.`,
)
